# Generated by Django 5.2.1 on 2025-06-30 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('idNumber', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('sku', models.CharField(default=0, max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TechSolutionsApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.AutoField(primary_key=True, serialize=False)),
                ('productQuantity', models.PositiveIntegerField()),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechSolutionsApp.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('idNumber', models.PositiveIntegerField(unique=True)),
                ('phoneNumber', models.PositiveIntegerField(unique=True)),
                ('passwordHash', models.CharField(default='', max_length=128)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TechSolutionsApp.role')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('saleId', models.AutoField(primary_key=True, serialize=False)),
                ('saleDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('discountPercentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TechSolutionsApp.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TechSolutionsApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('saleDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TechSolutionsApp.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechSolutionsApp.sale')),
            ],
            options={
                'unique_together': {('sale', 'product')},
            },
        ),
    ]
